server:
  port: 16000
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #开启健康检查
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:8761/eureka/

#代理服务子模块
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 60000
  routes:
    archetype-base:
      path: /base/**
      serviceId: archetype-base
      # 会去除掉 path 前缀
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    archetype-app:
      path: /app/**
      serviceId: archetype-app
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
